version: '3'
services: 
    react:
        stdin_open: true
        build: .
        ports:
            - "3000:3000"
        container_name: chatbot-web
        volumes: 
            - /app/node_modules
            - ./:/app